
export const MOTIVATIONAL_QUOTES: string[] = [
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "It is during our darkest moments that we must focus to see the light.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "The best way to predict the future is to create it.",
  "Patience is not simply the ability to wait - it's how we behave while we're waiting.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Do not wait for a perfect moment, take the moment and make it perfect.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "The mind is everything. What you think you become.",
  "Start where you are. Use what you have. Do what you can.",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
  "If you want to lift yourself up, lift up someone else.",
  "The best revenge is massive success.",
  "Your time is limited, don't waste it living someone else's life.",
  "The only impossible journey is the one you never begin.",
  "Keep your eyes on the stars, and your feet on the ground.",
  "The journey of a thousand miles begins with a single step.",
  "Strive not to be a success, but rather to be of value.",
  "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.",
  "The true entrepreneur is a doer, not a dreamer.",
  "Innovation distinguishes between a leader and a follower.",
  "Don't let yesterday take up too much of today.",
  "We may encounter many defeats but we must not be defeated.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Set your goals high, and don't stop till you get there.",
  "The secret of getting ahead is getting started.",
  "If you can dream it, you can achieve it.",
];
